// <auto-generated />
// Regenerate from compiled UE metadata; do not edit by hand.
using System.Collections.Immutable;
using GodotAls.Core.Animation;
namespace GodotAls.Animation.Lyra;
internal enum LyraLayerHook
{
    @FullBody_Aiming = 0,
    @FullBody_CycleState = 1,
    @FullBody_FallLandState = 2,
    @FullBody_FallLoopState = 3,
    @FullBody_IdleState = 4,
    @FullBody_JumpApexState = 5,
    @FullBody_JumpStartLoopState = 6,
    @FullBody_JumpStartState = 7,
    @FullBody_PivotState = 8,
    @FullBody_SkeletalControls = 9,
    @FullBody_StartState = 10,
    @FullBody_StopState = 11,
    @FullBodyAdditives = 12,
    @LeftHandPose_OverrideState = 13,
}
internal static class LyraGeneratedLayerContract
{
    internal const string SourceSha256 = "d582a274a0693618886e57887719ba90abd7c1f7de26c3dba6d707c236d8bb64";
    internal const string InterfaceClass = "/Game/Characters/Heroes/Mannequin/Animations/LinkedLayers/ALI_ItemAnimLayers.ALI_ItemAnimLayers_C";
    internal static readonly ImmutableArray<AlsAnimationLayerSignature> Declarations =
    [
        new("FullBody_Aiming", "ItemAnimLayers", false, ["PreAimPose"], [new("AimYaw", AlsAnimationLayerScalarType.Double, false), new("AimPitch", AlsAnimationLayerScalarType.Double, false)], -1f, -1f, "", ""),
        new("FullBody_CycleState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_FallLandState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_FallLoopState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_IdleState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_JumpApexState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_JumpStartLoopState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_JumpStartState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_PivotState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_SkeletalControls", "ItemAnimLayers", false, ["InPose"], [], -1f, -1f, "", ""),
        new("FullBody_StartState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBody_StopState", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("FullBodyAdditives", "ItemAnimLayers", false, [], [], -1f, -1f, "", ""),
        new("LeftHandPose_OverrideState", "ItemAnimLayers", false, ["InputPose"], [], -1f, -1f, "", ""),
    ];
    internal static readonly ImmutableDictionary<LyraLayerHook, AlsAnimationLayerSignature> Functions =
        Declarations.ToImmutableDictionary(f => Enum.Parse<LyraLayerHook>(f.Name));
    internal static void Validate(AlsAnimationLayerClassContract declaration)
    {
        if (declaration.ClassPath != InterfaceClass || declaration.Functions.Length != Declarations.Length)
            throw new InvalidOperationException("Generated animation interface differs.");
        foreach (var expected in Declarations)
        {
            var actual = declaration.Function(expected.Name);
            if (!expected.Accepts(actual) || expected.Group != actual.Group || expected.Implemented != actual.Implemented ||
                expected.BlendInTime != actual.BlendInTime || expected.BlendOutTime != actual.BlendOutTime ||
                expected.BlendInProfile != actual.BlendInProfile || expected.BlendOutProfile != actual.BlendOutProfile)
                throw new InvalidOperationException("Generated animation signature differs: " + expected.Name);
        }
    }
}
internal readonly record struct LyraFullBody_AimingParameters(double @AimYaw, double @AimPitch);
internal readonly ref struct LyraFullBody_AimingPoseInputs
{
    internal readonly LyraLayerPoseInput @PreAimPose;
    internal LyraFullBody_AimingPoseInputs(LyraLayerPoseInput @PreAimPose)
    {
        this.@PreAimPose = @PreAimPose;
    }
}
internal readonly ref struct LyraFullBody_SkeletalControlsPoseInputs
{
    internal readonly LyraLayerPoseInput @InPose;
    internal LyraFullBody_SkeletalControlsPoseInputs(LyraLayerPoseInput @InPose)
    {
        this.@InPose = @InPose;
    }
}
internal readonly ref struct LyraLeftHandPose_OverrideStatePoseInputs
{
    internal readonly LyraLayerPoseInput @InputPose;
    internal LyraLeftHandPose_OverrideStatePoseInputs(LyraLayerPoseInput @InputPose)
    {
        this.@InputPose = @InputPose;
    }
}
