using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using GodotAls.Core.Animation;

namespace GodotAls.Import;

public sealed record AlsAnimationLayerCodegenOptions(string Namespace, string Prefix, string PoseInputType);

// Emits ABI declarations and argument containers. Graph algorithms and instance
// lifecycle remain the executor's responsibility; codegen does not invent them.
public static class AlsAnimationLayerCodeGenerator
{
    public static string Generate(AlsAnimationLayerCatalog catalog, string interfaceClass,
        AlsAnimationLayerCodegenOptions options, IReadOnlyDictionary<string, int> ordinals)
    {
        foreach (var part in options.Namespace.Split('.')) Identifier(part);
        Identifier(options.Prefix); Identifier(options.PoseInputType);
        var functions = catalog.Class(interfaceClass).Functions;
        if (ordinals.Values.Any(n => n < 0) || ordinals.Values.Distinct().Count() != ordinals.Count ||
            functions.Any(f => !ordinals.ContainsKey(f.Name)))
            throw new InvalidOperationException("Incomplete or ambiguous animation function ordinal registry.");
        var ordered = functions.OrderBy(f => ordinals[f.Name]).ToArray();
        foreach (var function in ordered)
        {
            Identifier(function.Name);
            foreach (var name in function.InputPoses.Concat(function.Parameters.Select(p => p.Name))) Identifier(name);
        }
        var prefix = options.Prefix; var code = new StringBuilder();
        code.AppendLine("// <auto-generated />");
        code.AppendLine("// Regenerate from compiled UE metadata; do not edit by hand.");
        code.AppendLine("using System.Collections.Immutable;");
        code.AppendLine("using GodotAls.Core.Animation;");
        code.AppendLine($"namespace {options.Namespace};");
        code.AppendLine($"internal enum {prefix}LayerHook"); code.AppendLine("{");
        foreach (var f in ordered) code.AppendLine($"    @{f.Name} = {ordinals[f.Name]},");
        code.AppendLine("}");
        code.AppendLine($"internal static class {prefix}GeneratedLayerContract"); code.AppendLine("{");
        code.AppendLine($"    internal const string SourceSha256 = {Quote(catalog.SourceSha256)};");
        code.AppendLine($"    internal const string InterfaceClass = {Quote(interfaceClass)};");
        code.AppendLine("    internal static readonly ImmutableArray<AlsAnimationLayerSignature> Declarations =");
        code.AppendLine("    [");
        foreach (var f in ordered)
        {
            var poses = string.Join(", ", f.InputPoses.Select(Quote));
            var parameters = string.Join(", ", f.Parameters.Select(p =>
                $"new({Quote(p.Name)}, AlsAnimationLayerScalarType.{p.Type}, {Bool(p.ClassBound)})"));
            code.AppendLine($"        new({Quote(f.Name)}, {Quote(f.Group)}, {Bool(f.Implemented)}, [{poses}], [{parameters}], " +
                $"{Float(f.BlendInTime)}, {Float(f.BlendOutTime)}, {Quote(f.BlendInProfile)}, {Quote(f.BlendOutProfile)}),");
        }
        code.AppendLine("    ];");
        code.AppendLine($"    internal static readonly ImmutableDictionary<{prefix}LayerHook, AlsAnimationLayerSignature> Functions =");
        code.AppendLine($"        Declarations.ToImmutableDictionary(f => Enum.Parse<{prefix}LayerHook>(f.Name));");
        code.AppendLine("    internal static void Validate(AlsAnimationLayerClassContract declaration)"); code.AppendLine("    {");
        code.AppendLine("        if (declaration.ClassPath != InterfaceClass || declaration.Functions.Length != Declarations.Length)");
        code.AppendLine("            throw new InvalidOperationException(\"Generated animation interface differs.\");");
        code.AppendLine("        foreach (var expected in Declarations)"); code.AppendLine("        {");
        code.AppendLine("            var actual = declaration.Function(expected.Name);");
        code.AppendLine("            if (!expected.Accepts(actual) || expected.Group != actual.Group || expected.Implemented != actual.Implemented ||");
        code.AppendLine("                expected.BlendInTime != actual.BlendInTime || expected.BlendOutTime != actual.BlendOutTime ||");
        code.AppendLine("                expected.BlendInProfile != actual.BlendInProfile || expected.BlendOutProfile != actual.BlendOutProfile)");
        code.AppendLine("                throw new InvalidOperationException(\"Generated animation signature differs: \" + expected.Name);");
        code.AppendLine("        }"); code.AppendLine("    }"); code.AppendLine("}");
        foreach (var f in ordered)
        {
            if (f.Parameters.Length != 0)
                code.AppendLine($"internal readonly record struct {prefix}{f.Name}Parameters(" +
                    string.Join(", ", f.Parameters.Select(p => $"{Type(p.Type)} @{p.Name}")) + ");");
            if (f.InputPoses.Length == 0) continue;
            code.AppendLine($"internal readonly ref struct {prefix}{f.Name}PoseInputs"); code.AppendLine("{");
            foreach (var p in f.InputPoses) code.AppendLine($"    internal readonly {options.PoseInputType} @{p};");
            code.AppendLine($"    internal {prefix}{f.Name}PoseInputs(" +
                string.Join(", ", f.InputPoses.Select(p => $"{options.PoseInputType} @{p}")) + ")");
            code.AppendLine("    {");
            foreach (var p in f.InputPoses) code.AppendLine($"        this.@{p} = @{p};");
            code.AppendLine("    }"); code.AppendLine("}");
        }
        return code.ToString().Replace("\r\n", "\n");
    }
    private static void Identifier(string name)
    {
        if (!Regex.IsMatch(name, @"^[_\p{L}\p{Nl}][_\p{L}\p{Nl}\p{Nd}\p{Pc}\p{Mn}\p{Mc}\p{Cf}]*$"))
            throw new InvalidOperationException("Unsupported generated C# identifier: " + name);
    }
    private static string Quote(string value) => JsonSerializer.Serialize(value);
    private static string Bool(bool value) => value ? "true" : "false";
    private static string Float(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
    private static string Type(AlsAnimationLayerScalarType type) => type switch
    {
        AlsAnimationLayerScalarType.Boolean => "bool", AlsAnimationLayerScalarType.Int32 => "int",
        AlsAnimationLayerScalarType.Int64 => "long", AlsAnimationLayerScalarType.Single => "float",
        AlsAnimationLayerScalarType.Double => "double", _ => throw new ArgumentOutOfRangeException(nameof(type)),
    };
}
